name: Godot Windows Build

on:
  push:
    branches:
      - main  # Adjust if your default branch is different
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest  # Using Ubuntu to run the workflow

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Godot
        run: |
          GODOT_VERSION="4.3"
          wget https://downloads.tuxfamily.org/godotengine/$GODOT_VERSION/Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip
          unzip Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip -d godot
          chmod +x godot/Godot_v${GODOT_VERSION}-stable_linux.x86_64

      - name: Set Up Export Templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates/$GODOT_VERSION.stable/
          wget https://downloads.tuxfamily.org/godotengine/$GODOT_VERSION/Godot_v${GODOT_VERSION}-stable_export_templates.tpz
          unzip Godot_v${GODOT_VERSION}-stable_export_templates.tpz -d ~/.local/share/godot/export_templates/$GODOT_VERSION.stable/

      - name: Export Windows Build
        run: |
          mkdir -p build/windows
          godot/Godot_v${GODOT_VERSION}-stable_linux.x86_64 --headless --export-release "Windows Desktop" build/windows/game.exe

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: game-windows
          path: build/windows/game.exe
