name: Godot Build

on:
  push:
    branches:
      - main  # Change this to your branch name if needed
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Godot
        run: |
          GODOT_VERSION="4.3"  # Change to match your version
          wget https://github.com/godotengine/godot/releases/download/$GODOT_VERSION-stable/Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip
          unzip Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip
          mv Godot_v${GODOT_VERSION}-stable_linux.x86_64 godot
          chmod +x godot

      - name: Build Game
        run: |
          ./godot --export-release "Linux/X11" ./build/game.x86_64

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: game-build
          path: build/game.x86_64
